# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'KDYWeChat' do

pod 'SnapKit'

pod 'SwiftyJSON'
pod 'Alamofire', '~> 3.4.0'
pod 'Kingfisher'

pod 'Moya'
pod 'Moya/RxSwift'
pod 'RxSwift', '~> 2.5.0'
pod 'RxCocoa', '~> 2.5.0'
pod 'RxDataSources', '~> 0.8.1'

pod 'SVProgressHUD'

end

target 'KDYWeChatTests' do

end

target 'KDYWeChatUITests' do

end

