
source 'https://github.com/Artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

pod 'BlocksKit'
pod 'KVOController'
pod 'RxSwift', '~> 2.5.0'
pod 'Alamofire', '~> 3.4.0'
pod 'Kingfisher', '~> 2.4.1'
pod 'SwiftyJSON'

