
source 'https://github.com/Artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

pod 'BlocksKit'
pod 'KVOController'
pod 'JSPatch', '~> 1.0'
pod 'SnapKit'

pod 'SwiftyJSON'
pod 'Alamofire', '~> 3.4.0'
pod 'Kingfisher', '~> 2.4.1'

# Rx
pod 'RxSwift', '~> 2.5.0'
pod 'RxCocoa', '~> 2.5.0'
pod 'RxDataSources', '~> 0.8.1'

